---
# tasks file for dovecot
- name: Install Dovecot
  apt:
    name: dovecot
    state: latest

- name: Configure Dovecot
  template:
    src: templates/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable Dovecot service
  systemd:
    name: dovecot
    enabled: yes
