---
# tasks file for nginx
- name: "Update apt cache"
  become: true
  apt:
    update_cache: yes


- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Enable Nginx service
  systemd:
    name: nginx
    enabled: yes
